// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';

// ...

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVQkhmE50eLcjI_ABVAKXz1mYSwktBml8',
    appId: '1:429505727532:web:fad20e062941f8ab1f1589',
    messagingSenderId: '429505727532',
    projectId: 'flutterapplication1-72f40',
    authDomain: 'flutterapplication1-72f40.firebaseapp.com',
    storageBucket: 'flutterapplication1-72f40.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlPmJXUeIs-6PuvqpYWnmrZ16ML2mxnuA',
    appId: '1:429505727532:android:1f252b25142196ef1f1589',
    messagingSenderId: '429505727532',
    projectId: 'flutterapplication1-72f40',
    storageBucket: 'flutterapplication1-72f40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd3wTIdIKzMHSbLWIL76fQhZlMAQCx_Zw',
    appId: '1:429505727532:ios:b8b0753b5edbc2321f1589',
    messagingSenderId: '429505727532',
    projectId: 'flutterapplication1-72f40',
    storageBucket: 'flutterapplication1-72f40.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd3wTIdIKzMHSbLWIL76fQhZlMAQCx_Zw',
    appId: '1:429505727532:ios:d039f289830701a01f1589',
    messagingSenderId: '429505727532',
    projectId: 'flutterapplication1-72f40',
    storageBucket: 'flutterapplication1-72f40.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
